title: fx_hoc_hosting - Hosting for multi fx document

# port which master site listen on
port: 8080

# begin port which sites listen on
doc_port: 9000

# organization information
org:
    name: Stark Industries
    url: https://en.wikipedia.org/wiki/Stark_Industries

# user and password which is uses to access documents
auth:
    user: root
    password: root

sites:
    - url: https://github.com/kevin-leptons/fx-doc.git
      branch: master
      doc: doc
    - url: https://github.com/kevin-leptons/fx-doc.git
      branch: master
      doc: doc
